export const CHANGE_FIRST_NAME = "CHANGE_FIRST_NAME";
export const CHANGE_LAST_NAME = "CHANGE_LAST_NAME";
export const CHANGE_PROFILE_PHOTO = "CHANGE_PROFILE_PHOTO";
export const CHANGE_ROUNDED_CORNER = "CHANGE_ROUNDED_CORNER";
export const SET_ACCOUNT_INITIAL_STATE = "SET_ACCOUNT_INITIAL_STATE";
