// TASKS
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const CREATE_CATEGORY_TASK = "CREATE_UNKNOW_CATEGORY_TASK";
export const EDIT_TASK = "EDIT_TASK";
// CATEGORIES
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
// STATE
export const SET_INITIAL_STATE = "SET_INITIAL_STATE";
